#info for reaching the registry
server:
  host: localhost
  port: 60001
  
request_parameters:
  registry:
    ip: localhost
    port: 60005
  path:
    registry_get: /r/get
    registry_put: /r/put
    registry_delete: /r/delete

