#info for reaching the registry
server:
  host: localhost
  port: 8089
  
request_parameters:
  registry:
    ip: localhost
    port: 8090
  path:
    registry_get: /r/get
    registry_put: /r/put
    registry_delete: /r/delete
    registry_invoke: /r/invokeCC

