#info for reaching the registry
default:
  server:
    host: localhost
    port: 60005
  
  request_parameters:
    host: localhost
    port: 60005
    path:
      registry_get: /r/get
      registry_put: /r/put
      registry_delete: /r/delete

